jediacademy/quest/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import ExamCreateView, ExamDetailView, create_answers_view


urlpatterns = [
    url(r'exam/person/(?P<applicant_id>\d+)/create/$',
        ExamCreateView.as_view(), name='exam-create'),
    url(r'exam/(?P<pk>\d+)/detail/$',
        ExamDetailView.as_view(), name='exam-detail'),
    url(r'exam/(?P<exam_id>\d+)/process/$',
        create_answers_view, name='answers-create'),
    url(
        r'exam/afterparty/$',
        TemplateView.as_view(template_name='quest/afterparty.html'),
        name='afterparty'
    ),
]

jediacademy/quest/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext as _

from ranking.models import Rank
from reception.models import Person


class Quest(models.Model):
    rank = models.ForeignKey(Rank, on_delete=models.PROTECT)
    descr = models.TextField(_("description"))

    class Meta:
        verbose_name = _("quest")
        verbose_name_plural = _("quests")
        unique_together = ('rank', 'descr', )

    def __str__(self):
        return "Level={}; {}...".format(
            self.rank.name, self.descr[:21]
        )


class Task(models.Model):
    quest = models.ForeignKey(Quest, on_delete=models.PROTECT)
    question = models.TextField(_("question"))

    class Meta:
        verbose_name = _("task")
        verbose_name_plural = _("tasks")
        unique_together = ('quest', 'question', )

    def __str__(self):
        return "{}; Question={}...".format(
            self.quest, self.question[:21]
        )


class Exam(models.Model):
    person = models.ForeignKey(Person, on_delete=models.PROTECT)
    quest = models.ForeignKey(Quest, on_delete=models.PROTECT)

    class Meta:
        verbose_name = _("exam")
        verbose_name_plural = _("exams")
        unique_together = ('person', 'quest', )

    def __str__(self):
        return "Person={}; Quest-{}".format(
            self.person, self.quest
        )

    def get_absolute_url(self):
        return reverse('exam-detail', args=[str(self.id)])


class Answer(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.PROTECT)
    task = models.ForeignKey(Task, on_delete=models.PROTECT)
    actual_question_text = models.TextField(_("actual question text"))
    choice = models.BooleanField(_("choice"))

    class Meta:
        verbose_name = _("answer")
        verbose_name_plural = _("answers")
        unique_together = ('exam', 'task', )

    def __str__(self):
        return "{} Task question={}...; Choice is {}".format(
            self.exam, self.task.question[:21], self.choice
        )

jediacademy/quest/forms.py
from django.forms import inlineformset_factory, HiddenInput, Textarea

from .models import Exam, Answer


AnswerInlineModelFormSet = inlineformset_factory(
    Exam,
    Answer,
    fields=('exam', 'task', 'actual_question_text', 'choice', ),
    widgets={'exam': HiddenInput(), 'task': HiddenInput(),
             'actual_question_text': Textarea(attrs={'readonly': 'readonly'})},
    can_delete=False,
)

jediacademy/quest/views.py
from django.views.generic import CreateView, DetailView
from django.shortcuts import render, redirect

from .forms import AnswerInlineModelFormSet
from .models import Exam


class ExamCreateView(CreateView):
    model = Exam
    fields = ('person', 'quest', )


class ExamDetailView(DetailView):
    model = Exam


def create_answers_view(request, exam_id, *args, **kwargs):
    exam = Exam.objects.get(id=exam_id)
    if request.method == "POST":
        formset = AnswerInlineModelFormSet(request.POST, instance=exam)
        if formset.is_valid():
            formset.save()
            return redirect('afterparty')
    if request.method == "GET":
        tasks = exam.quest.task_set.all()
        initial = [{'exam': exam_id, 'task': t.id, 'actual_question_text': t.question} for t in tasks]
        formset = AnswerInlineModelFormSet(instance=exam, initial=initial)
    return render(request, 'quest/answers_create.html', {'formset': formset})

jediacademy/quest/templates/quest/afterparty.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}
    <div class="container">
        <h2>{% trans 'Thx a lot! =)' %}</h2>
        <hr>
{% endblock content %}

jediacademy/quest/templates/quest/answers_create.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}
    <div class="container">
        <h2>Questions</h2>
        <hr>
        <form method="post" action="">
            {{ formset.management_form }}
            {% csrf_token %}
            {% for form in formset %}
                {{ form.as_p }}
                <hr>
            {% endfor %}
            <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
        </form>
{% endblock content %}

jediacademy/quest/templates/quest/exam_detail.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2>{% trans 'Your Exam' %}</h2>
                <hr>
                <p>
                    <span>{% trans 'Person:' %}</span>
                    {{ object.person.lastname }} {{ object.person.firstname }} {% trans 'from' %} {{ object.person.planet }}
                </p>
                <p>
                    <span>{% trans 'Quest description:' %}</span>
                    {{ object.quest.descr }}
                </p>
                <p>
                    <span>{% trans 'Quest Level:' %}</span>
                    {{ object.quest.rank }}
                </p>
                <hr>
                <p><a class="btn btn-primary btn-lg" href="{% url 'answers-create' object.id %}" role="button">{% trans 'Open tasks' %}</a></p>
            </div>
        </div>
    </div>
{% endblock content %}

jediacademy/quest/templates/quest/exam_form.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-4">
            </div>
            <div class="col-xs-12 col-md-4">
                <h1>{% trans 'Choose the Quest' %}</h1>
                <hr>
                <form action="{{ action }}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.non_field_errors }}
                    </div>
                    <input hidden="true" name="person" id="id_person" type="text" value="{{ view.kwargs.applicant_id }}">
                    <div class="form-group">
                        {% if form.quest.errors %}
                            <ol>
                            {% for error in form.quest.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                            </ol>
                        {% endif %}
                        <label for="id_quest">{% trans 'Quest:' %}</label>
                        <select class="form-control" name="quest" id="id_quest" required="">
                            {% for x,y in form.fields.quest.choices %}
                                <option value="{{ x }}"{% if form.fields.quest.value == x %} selected{% endif %}>{{ y }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-xs-12 col-md-4">
            </div>
        </div>
    </div>
{% endblock content %}