jediacademy/quest/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import ExamCreateView, ExamDetailView, create_answers_view


urlpatterns = [
    url(r'exam/person/(?P<applicant_id>\d+)/create/$',
        ExamCreateView.as_view(), name='exam-create'),
    url(r'exam/(?P<pk>\d+)/detail/$',
        ExamDetailView.as_view(), name='exam-detail'),
    url(r'exam/(?P<exam_id>\d+)/process/$',
        create_answers_view, name='answers-create'),
    url(
        r'exam/afterparty/$',
        TemplateView.as_view(template_name='quest/afterparty.html'),
        name='afterparty'
    ),
]

jediacademy/reception/urls.py
from django.conf.urls import url

from .views import MainPageView, PersonCreateView, PersonDetailView


urlpatterns = [
    url(r'^$',
        MainPageView.as_view(), name='mainpage'),
    url(r'^person/create/$',
        PersonCreateView.as_view(), name='person-create'),
    url(r'^person/(?P<pk>\d+)/detail/$',
        PersonDetailView.as_view(), name='person-detail'),
]

jediacademy/reception/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext as _


class Planet(models.Model):
    name = models.CharField(_("name"), max_length=50, unique=True)

    class Meta:
        verbose_name = _("planet")
        verbose_name_plural = _("planets")

    def __str__(self):
        return self.name


class Person(models.Model):
    planet = models.ForeignKey(Planet, on_delete=models.PROTECT)
    lastname = models.CharField(_("lastname"), max_length=50)
    firstname = models.CharField(_("firstname"), max_length=50)
    email = models.EmailField(_("email"), unique=True)

    class Meta:
        verbose_name = _("person")
        verbose_name_plural = _("persons")

    def __str__(self):
        return "{} {}; From={}".format(
            self.lastname, self.firstname, self.planet)

    def get_absolute_url(self):
        return reverse('person-detail', args=[str(self.id)])

jediacademy/reception/views.py
from django.views.generic import TemplateView, CreateView, DetailView
from django.urls import reverse_lazy

from .models import Person


class MainPageView(TemplateView):
    template_name = 'reception/main_page.html'


class PersonCreateView(CreateView):
    model = Person
    fields = ('lastname', 'firstname', 'planet', 'email', )

    def get_success_url(self):
        return reverse_lazy('exam-create',
                            kwargs={'applicant_id': self.object.id})


class PersonDetailView(DetailView):
    model = Person

jediacademy/reception/templates/reception/main_page.html
{% extends "base/base.html" %}

{% load i18n %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="jumbotron">
                    <h1>{% trans 'Welcome to JA!' %}</h1>
                    <p>{% lorem 1 %}</p>
                    <p><a class="btn btn-primary btn-lg" href="{% url 'person-create' %}" role="button">{% trans 'I\'m Youngling' %}</a></p>
                    <p><a class="btn btn-primary btn-lg" href="{% url 'person-create' %}" role="button">{% trans 'For Mentors Only ...' %}</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

jediacademy/reception/templates/reception/person_detail.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}
    <div class="container">
        <h2>Applicant</h2>
        <hr>
        <div class="person-detail">
            <div><span>{% trans 'lastname:' %}</span>{{ object.lastname }}</div>
            <div><span>{% trans 'firstname:' %}</span>{{ object.firstname }}</div>
            <div><span>{% trans 'email:' %}</span>{{ object.email }}</div>
            <div><span>{% trans 'planet:' %}</span>{{ object.planet }}</div>
        </div>
        <hr>
        <p><a class="btn btn-primary btn-lg" role="button" href="{% url 'exam-create'  object.id %}">{% trans 'Take the Exam' %}</a></p>
    </div>
{% endblock content %}

jediacademy/reception/templates/reception/person_form.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-4">
            </div>
            <div class="col-xs-12 col-md-4">
                <h1>{% trans 'Applicant Registration' %}</h1>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.non_field_errors }}
                    </div>
                    <div class="form-group">
                        {% if form.email.errors %}
                            <ol>
                            {% for error in form.email.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                            </ol>
                        {% endif %}
                        <label for="id_email">{% trans 'Email address:' %}</label>
                        <input type="email" class="form-control" name="email" id="id_email" type="email" maxlength="254" required="" >
                    </div>
                    <div class="form-group">
                        {% if form.lastname.errors %}
                            <ol>
                            {% for error in form.lastname.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                            </ol>
                        {% endif %}
                        <label for="id_lastname">{% trans 'Lastname:' %}</label>
                        <input class="form-control" name="lastname" id="id_lastname" type="text" maxlength="50" required="">
                    </div>
                    <div class="form-group">
                        {% if form.firstname.errors %}
                            <ol>
                            {% for error in form.firstname.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                            </ol>
                        {% endif %}
                        <label for="id_firstname">{% trans 'Firstname:' %}</label>
                        <input class="form-control" name="firstname" id="id_firstname" type="text" maxlength="50" required="">
                    </div>
                    <div class="form-group">
                        {% if form.planet.errors %}
                            <ol>
                            {% for error in form.planet.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                            </ol>
                        {% endif %}
                        <label for="id_planet">{% trans 'Planet:' %}</label>
                        <select class="form-control" name="planet" id="id_planet" required="">
                            {% for x,y in form.fields.planet.choices %}
                                <option value="{{ x }}"{% if form.fields.planet.value == x %} selected{% endif %}>{{ y }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-xs-12 col-md-4">
            </div>
        </div>
    </div>
{% endblock content %}